services:
  - type: web
    name: yt-shorts-downloader
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
